### ISSUE TITLE
Can't open cover with screwdriver during SMP due missing class

### ISSUE THREAD

**Issue by stephan48** [solidDoWant/GregTech-Energistics#1]
Hi,

My Version is: 1.0.0.1
On the Omnifactory Pack(devish version) running in a dedicated server.

As soon as i try to open the cover with a screwdriver i get the following on the server:
Jan 30 13:13:22 minestuff launch.sh[17744]: [13:13:22] [Server thread/FATAL] [VanillaFix]: Error executing task
Jan 30 13:13:22 minestuff launch.sh[17744]: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
Jan 30 13:13:22 minestuff launch.sh[17744]:         at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Jan 30 13:13:22 minestuff launch.sh[17744]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.soliddowant.gregtechenergistics.covers.CoverStatus.toString(CoverStatus.java:27) ~[CoverStatus.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.lambda$createUI$4(CoverAE2Stocker.java:344) ~[CoverAE2Stocker.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.gui.widgets.SimpleTextWidget.detectAndSendChanges(SimpleTextWidget.java:59) ~[SimpleTextWidget.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.gui.widgets.AbstractWidgetGroup.detectAndSendChanges(AbstractWidgetGroup.java:209) ~[AbstractWidgetGroup.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.google.common.collect.ImmutableMapKeySet.lambda$forEach$0(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.google.common.collect.RegularImmutableBiMap$Inverse.lambda$forEach$0(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.google.common.collect.RegularImmutableBiMap.forEach(RegularImmutableBiMap.java:153) ~[minecraft_server.1.12.2.jar:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.google.common.collect.RegularImmutableBiMap$Inverse.forEach(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.google.common.collect.ImmutableMapKeySet.forEach(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.gui.UIFactory.openUI(UIFactory.java:54) ~[UIFactory.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.cover.CoverWithUI.openUI(CoverWithUI.java:10) ~[CoverWithUI.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.onScrewdriverClick(CoverAE2Stocker.java:290) ~[CoverAE2Stocker.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.metatileentity.MetaTileEntity.onCoverScrewdriverClick(MetaTileEntity.java:309) ~[MetaTileEntity.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at gregtech.api.block.machines.BlockMachine.onBlockActivated(BlockMachine.java:278) ~[BlockMachine.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161]
Jan 30 13:13:22 minestuff launch.sh[17744]:         at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
Jan 30 13:13:22 minestuff launch.sh[17744]:         ... 5 more

A bit of googling gives me this:
https://forums.minecraftforge.net/topic/67783-server-chrashes-on-startup/
https://github.com/refinedmods/refinedstorage/issues/106
https://github.com/refinedmods/refinedstorage/commit/b970ac3a8ac24137de1452b3f3a22294c98d4bb5

Maybe the fix is as simple as in the mentioned RefinedStorage commit?

Kind Regards,
Stephan

**Comment by TBXin** [comment]
Hello, confirmed. Same issue on dev Omnifactory server instance (Omnifactory-dev-144c273-snapshot-server).
Additional mods: appliedenergistics2-rv6-stable-7.omni-fixes-v16c.jar (pae2), GregtechEnergistics-1.0.0.1.jar.

`[16:33:06] [Server thread/FATAL] [VanillaFix]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.soliddowant.gregtechenergistics.covers.CoverStatus.toString(CoverStatus.java:27) ~[CoverStatus.class:?]
        at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.lambda$createUI$4(CoverAE2Stocker.java:344) ~[CoverAE2Stocker.class:?]
        at gregtech.api.gui.widgets.SimpleTextWidget.detectAndSendChanges(SimpleTextWidget.java:59) ~[SimpleTextWidget.class:?]
        at gregtech.api.gui.widgets.AbstractWidgetGroup.detectAndSendChanges(AbstractWidgetGroup.java:209) ~[AbstractWidgetGroup.class:?]
        at com.google.common.collect.ImmutableMapKeySet.lambda$forEach$0(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap$Inverse.lambda$forEach$0(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap.forEach(RegularImmutableBiMap.java:153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap$Inverse.forEach(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.ImmutableMapKeySet.forEach(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
        at gregtech.api.gui.UIFactory.openUI(UIFactory.java:54) ~[UIFactory.class:?]
        at gregtech.api.cover.CoverWithUI.openUI(CoverWithUI.java:10) ~[CoverWithUI.class:?]
        at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.onScrewdriverClick(CoverAE2Stocker.java:290) ~[CoverAE2Stocker.class:?]
        at gregtech.api.metatileentity.MetaTileEntity.onCoverScrewdriverClick(MetaTileEntity.java:311) ~[MetaTileEntity.class:?]
        at gregtech.api.block.machines.BlockMachine.onBlockActivated(BlockMachine.java:278) ~[BlockMachine.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at com.soliddowant.gregtechenergistics.covers.CoverStatus.toString(CoverStatus.java:27) ~[CoverStatus.class:?]
        at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.lambda$createUI$4(CoverAE2Stocker.java:344) ~[CoverAE2Stocker.class:?]
        at gregtech.api.gui.widgets.SimpleTextWidget.detectAndSendChanges(SimpleTextWidget.java:59) ~[SimpleTextWidget.class:?]
        at gregtech.api.gui.widgets.AbstractWidgetGroup.detectAndSendChanges(AbstractWidgetGroup.java:209) ~[AbstractWidgetGroup.class:?]
        at com.google.common.collect.ImmutableMapKeySet.lambda$forEach$0(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap$Inverse.lambda$forEach$0(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap.forEach(RegularImmutableBiMap.java:153) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.RegularImmutableBiMap$Inverse.forEach(RegularImmutableBiMap.java:205) ~[minecraft_server.1.12.2.jar:?]
        at com.google.common.collect.ImmutableMapKeySet.forEach(ImmutableMapKeySet.java:72) ~[minecraft_server.1.12.2.jar:?]
        at gregtech.api.gui.UIFactory.openUI(UIFactory.java:54) ~[UIFactory.class:?]
        at gregtech.api.cover.CoverWithUI.openUI(CoverWithUI.java:10) ~[CoverWithUI.class:?]
        at com.soliddowant.gregtechenergistics.covers.CoverAE2Stocker.onScrewdriverClick(CoverAE2Stocker.java:290) ~[CoverAE2Stocker.class:?]
        at gregtech.api.metatileentity.MetaTileEntity.onCoverScrewdriverClick(MetaTileEntity.java:311) ~[MetaTileEntity.class:?]
        at gregtech.api.block.machines.BlockMachine.onBlockActivated(BlockMachine.java:278) ~[BlockMachine.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NullPointerException`

**Comment by solidDoWant** [comment]
Fixed and released: https://github.com/solidDoWant/GregTech-Energistics/releases/latest
CurseForge release here: https://www.curseforge.com/minecraft/mc-mods/gregtech-energistics/files/all
