### ISSUE TITLE
duplication ID

### ISSUE THREAD

**Issue by blakpsykozz27** [solidDoWant/GregTech-Energistics#2]
with the update of gregtech 1.16.0.750 there is a duplication id which makes crash the game

with tTime: 6/30/21 11:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GregTech Energistics (gregtechenergistics)
Caused by: java.lang.IllegalArgumentException: Tried to reassign id 40 to gregtech.api.cover.CoverDefinition@33e49947 (gregtechenergistics:ae2.interface.lv), but it is already assigned to gregtech.api.cover.CoverDefinition@18f687c0 (gregtech:fluid.regulator.lv)!
	at gregtech.api.util.GTControlledRegistry.register(GTControlledRegistry.java:50)
	at gregtech.api.cover.CoverDefinition.registerCover(CoverDefinition.java:28)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerBehavior(CoverBehaviors.java:41)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.registerStockerCover(CoverBehaviors.java:34)
	at com.soliddowant.gregtechenergistics.covers.CoverBehaviors.init(CoverBehaviors.java:19)
	at com.soliddowant.gregtechenergistics.CommonProxy.init(CommonProxy.java:24)
	at com.soliddowant.gregtechenergistics.ClientProxy.init(ClientProxy.java:19)
	at com.soliddowant.gregtechenergistics.GregTechEnergisticsMod.init(GregTechEnergisticsMod.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)e update of gregtech 1.16.0.750 there is a duplication id which makes crash the game

**Comment by FomaDima** [comment]
same problem

**Comment by magcicada** [comment]
https://github.com/solidDoWant/GregTech-Energistics/blob/693cf454e527ac22c731d08baf3e1878aa962a2f/src/main/java/com/soliddowant/gregtechenergistics/covers/CoverBehaviors.java#L17

**Comment by magcicada** [comment]
I change this ID to 50 and it works well.
